openapi: 3.0.0
info:
  title: Cart Service API
  description: Cart management microservice for AAW Marketplace
  version: 1.0.0
  contact:
    name: AAW Team

servers:
  - url: http://localhost:8001
    description: Local development server

paths:
  /api/cart:
    get:
      summary: Get all cart items
      tags:
        - Cart
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of cart items
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    post:
      summary: Add item to cart
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                quantity:
                  type: integer
                  minimum: 1
                  example: 1
      responses:
        '201':
          description: Item added to cart
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Product not found
        '500':
          description: Internal server error

    put:
      summary: Update cart item quantity
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cart_id
              properties:
                cart_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                quantity:
                  type: integer
                  minimum: 0
                  example: 2
      responses:
        '200':
          description: Cart item updated
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Cart item not found
        '500':
          description: Internal server error

    delete:
      summary: Delete cart item
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
              properties:
                product_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Cart item deleted
        '401':
          description: Unauthorized
        '404':
          description: Cart item not found
        '500':
          description: Internal server error

  /api/cart/v1:
    delete:
      summary: Delete cart item
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
              properties:
                product_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '204':
          description: Cart item deleted
        '401':
          description: Unauthorized
        '404':
          description: Cart item not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT