openapi: 3.0.0
info:
  title: Cart Service API
  description: Cart management microservice for AAW Marketplace
  version: 1.0.0
  contact:
    name: AAW Team

servers:
  - url: http://localhost:8001
    description: Local development server

paths:
  /api/cart:
    get:
      summary: Get all cart items
      tags:
        - Cart
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of cart items
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        product_id:
                          type: string
                          format: uuid
                        quantity:
                          type: integer
                        user_id:
                          type: string
                          format: uuid
        '401':
          description: Unauthorized

    post:
      summary: Add item to cart
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                quantity:
                  type: integer
                  minimum: 1
                  example: 1
      responses:
        '201':
          description: Item added to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Item added to cart"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      product_id:
                        type: string
                        format: uuid
                      quantity:
                        type: integer
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

    put:
      summary: Edit cart item
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cart_id
              properties:
                cart_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                quantity:
                  type: integer
                  minimum: 0
                  example: 2
      responses:
        '200':
          description: Cart item updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cart item updated"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      quantity:
                        type: integer
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Cart item not found

    delete:
      summary: Delete cart item
      tags:
        - Cart
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
              properties:
                product_id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Cart item deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cart item deleted"
        '401':
          description: Unauthorized
        '404':
          description: Cart item not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT