openapi: 3.0.0
info:
  title: Order Service API
  description: Order management microservice for AAW Marketplace
  version: 1.0.0
  contact:
    name: AAW Team

servers:
  - url: http://localhost:8001
    description: Local development server

paths:
  /api/order:
    get:
      summary: Get all orders
      tags:
        - Orders
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized

    post:
      summary: Place new order
      tags:
        - Orders
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - shipping_provider
              properties:
                shipping_provider:
                  type: string
                  enum: [JNE, TIKI, SICEPAT, GOSEND, GRAB_EXPRESS]
                  example: "JNE"
      responses:
        '201':
          description: Order placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /api/order/{orderId}:
    get:
      summary: Get order details
      tags:
        - Orders
      security:
        - BearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
        '404':
          description: Order not found

  /api/order/{orderId}/pay:
    post:
      summary: Pay for order
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - payment_method
                - payment_reference
                - amount
              properties:
                payment_method:
                  type: string
                  enum: [CREDIT_CARD, BANK_TRANSFER, E_WALLET]
                  example: "CREDIT_CARD"
                payment_reference:
                  type: string
                  example: "ref12345"
                amount:
                  type: integer
                  minimum: 1
                  example: 100
      responses:
        '200':
          description: Payment successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid payment details
        '404':
          description: Order not found

  /api/order/{orderId}/cancel:
    post:
      summary: Cancel order
      tags:
        - Orders
      security:
        - BearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
        '404':
          description: Order not found

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [PENDING, PAID, CANCELLED, COMPLETED]
        total_amount:
          type: number
          format: float
        created_at:
          type: string
          format: date-time
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: string
                format: uuid
              quantity:
                type: integer
              price:
                type: number
                format: float

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT