openapi: 3.0.0
info:
  title: Order Service API
  description: Order management microservice for AAW Marketplace
  version: 1.0.0
  contact:
    name: AAW Team

servers:
  - url: http://localhost:8001
    description: Local development server

paths:
  /api/order:
    get:
      summary: Get all orders
      tags:
        - Orders
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of orders
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    post:
      summary: Place new order
      tags:
        - Orders
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - shipping_provider
              properties:
                shipping_provider:
                  type: string
      responses:
        '201':
          description: Order placed successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/order/{orderId}:
    get:
      summary: Get order details
      tags:
        - Orders
      security:
        - BearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error

  /api/order/{orderId}/pay:
    post:
      summary: Pay for order
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - payment_method
                - payment_reference
                - amount
              properties:
                payment_method:
                  type: string
                payment_reference:
                  type: string
                  example: "ref12345"
                amount:
                  type: integer
                  minimum: 1
                  example: 100
      responses:
        '200':
          description: Payment successful
        '400':
          description: Invalid payment details
        '404':
          description: Order not found
        '500':
          description: Internal server error

  /api/order/{orderId}/cancel:
    post:
      summary: Cancel order
      tags:
        - Orders
      security:
        - BearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order cancelled successfully
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT