openapi: 3.0.0
info:
  title: Tenant Service API
  description: Tenant management microservice for AAW Marketplace
  version: 1.0.0
  contact:
    name: AAW Team

servers:
  - url: http://localhost:8003
    description: Local development server

paths:
  /api/tenant/{tenant_id}:
    get:
      summary: Get tenant by ID
      tags:
        - Tenants
      security:
        - BearerAuth: []
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Tenant details
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/tenant/{old_tenant_id}:
    put:
      summary: Update tenant
      tags:
        - Tenants
      security:
        - BearerAuth: []
      parameters:
        - name: old_tenant_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTenantRequest'
      responses:
        '200':
          description: Tenant updated successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/tenant:
    post:
      summary: Create new tenant
      tags:
        - Tenants
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantRequest'
      responses:
        '201':
          description: Tenant created successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      summary: Delete tenant
      tags:
        - Tenants
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_id
              properties:
                tenant_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Tenant deleted successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/tenant/v1/{tenant_id}:
    get:
      summary: Get tenant by ID
      tags:
        - Tenants
      security:
        - BearerAuth: []
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Tenant details
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    post:
      summary: Create new tenant
      tags:
        - Tenants
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantRequest'
      responses:
        '201':
          description: Tenant created successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      summary: Delete tenant
      tags:
        - Tenants
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_id
              properties:
                tenant_id:
                  type: string
                  format: uuid
      responses:
        '204':
          description: Tenant deleted successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
          
components:
  schemas:
    Tenant:
      type: object
      properties:
        id:
          type: string
          format: uuid
        owner_id:
          type: string
          format: uuid
        tenantDetails:
          $ref: '#/components/schemas/TenantDetails'

    TenantDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tenant_id:
          type: string
          format: uuid
        name:
          type: string

    CreateTenantRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    UpdateTenantRequest:
      type: object
      properties:
        tenant_id:
          type: string
          format: uuid
        owner_id:
          type: string
          format: uuid
        name:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT