apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-db-pvc
  namespace: wishlist
spec:
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi