apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: wishlist
spec:
  selector:
    app: wishlist-service
  ports:
  - port: 8004
    targetPort: 8000
    nodePort: 30004
  type: NodePort