apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: order
type: Opaque
stringData:
  jwt-secret: auth_ms_jwt_secret
  admin-jwt-secret: admin_auth_ms_jwt_secret
  db-host: order-db-service
  db-port: "5433"
  db-user: postgres
  db-password: postgres
  db-name: order_db