apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
spec:
  selector:
    app: order-service
  ports:
  - port: 8001
    targetPort: 8000
    nodePort: 30001
  type: NodePort