apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product
spec:
  selector:
    app: product-service
  ports:
  - port: 8002
    targetPort: 8000
    nodePort: 30002
  type: NodePort