version: "3.8"

services:
  tenant-service:
    build: .
    ports:
      - "8003:8000"
    environment:
      - TENANT_ID=9054983f-77b9-4db6-b2ff-fa4c858b0a1f
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=tenant-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tenant_db
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - tenant-db
    networks:
      - marketplace-network

  tenant-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - tenant_postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  tenant_postgres_data:

networks:
  marketplace-network:
    external: true
