version: '3.8'

services:
  product-service:
    build: .
    ports:
      - "8002:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=product_db
      - AUTH_SERVICE_URL=http://auth-service:8000
      - TENANT_SERVICE_URL=http://tenant-service:8003
    depends_on:
      - product-db
    networks:
      - marketplace-network

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  product_postgres_data:

networks:
  marketplace-network:
    external: true