version: '3.8'

services:
  wishlist-service:
    build: .
    ports:
      - "8004:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=wishlist-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wishlist_db
    depends_on:
      - wishlist-db
    networks:
      - marketplace-network

  wishlist-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - wishlist_postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  wishlist_postgres_data:

networks:
  marketplace-network:
    external: true