apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service
  namespace: tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant-service
  template:
    metadata:
      labels:
        app: tenant-service
    spec:
      containers:
        - name: tenant-service
          image: ferry11/tenant-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: tenant-id
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: admin-tenant-id
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: port
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: node-env
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: jwt-secret
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: admin-jwt-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: db-port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tenant-secrets
                  key: db-name
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: auth-service-url
