apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-db-pvc
  namespace: tenant
spec:
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi