apiVersion: v1
kind: Secret
metadata:
  name: tenant-secrets
  namespace: tenant
type: Opaque
stringData:
  jwt-secret: auth_ms_jwt_secret
  admin-jwt-secret: admin_auth_ms_jwt_secret
  db-host: tenant-db-service
  db-port: "5435"
  db-user: postgres
  db-password: postgres
  db-name: tenant_db