apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-db
  namespace: tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-db
  template:
    metadata:
      labels:
        app: tenant-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: db-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: db-password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: tenant-db-pvc