apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  namespace: tenant
spec:
  selector:
    app: tenant-service
  ports:
  - port: 8003
    targetPort: 8000
    nodePort: 30003
  type: NodePort