apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: authentication-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: tenant-id
        - name: ADMIN_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: admin-tenant-id
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: port
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: node-env
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: admin-jwt-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: db-name