apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
stringData:
  jwt-secret: auth_ms_jwt_secret
  admin-jwt-secret: admin_auth_ms_jwt_secret
  db-host: auth-db-service
  db-port: "5432"
  db-user: postgres
  db-password: postgres
  db-name: auth_db