version: "3.8"

services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TENANT_ID=9054983f-77b9-4db6-b2ff-fa4c858b0a1f
      - ADMIN_TENANT_ID=9054983f-77b9-4db6-b2ff-fa4c858b0a1f
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
    depends_on:
      - auth-db
    networks:
      - marketplace-network

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  auth_postgres_data:

networks:
  marketplace-network:
    external: true
